"""add is_verified to user

Revision ID: 634ce2c948ef
Revises: 0005
Create Date: 2026-05-06 17:25:38.206771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '634ce2c948ef'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
